image: inkytonik/docker-skink

pipelines:
  default:
    - step:
        caches:
            - sbt
            - ivy2
        script:
          - git submodule update --init
          - cd fshell-w2t
          - wget https://codeload.github.com/eliben/pycparser/zip/master -O pycparser-master.zip
          - unzip pycparser-master.zip
          - cd ..
          - sbt test
