#! /bin/sh
# cpacheckall file.c ...
#
# Check that all of the C files that have .verif files that specify
# FALSE results have correct witnesses in those files.

for file in $*
do
    base=`basename $file .c`
    verif=$base.verif
    if test -r $verif
    then
        case `head -1 $verif` in
            FALSE*)
                /bin/echo -n "$base "
                result=`../cpacheck ../ALL.prp $file $verif 2>&1 | grep '^Verification result:'`
                case $result in
                    Verification\ result:\ FALSE*)
                        echo ok
                        ;;
                    *)
                        echo fail
                        ;;
                esac
                ;;
            *)
                ;;
        esac
    fi
done
