#! /bin/sh
# Generate appropriate LLVM IR code for C programs on command-line.
# We assume the latest clang which is 3.7.0.

for file in $*
do
  echo $file
  base=${file%.*}
  llfile=$base.ll

  clangwargs="-Wno-implicit-function-declaration"
  clangargs="-c -emit-llvm -g -o - -S -x c $clangwargs"

  clang $clangargs $file | opt -S -inline -o $llfile
done
