name: Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Setup fshell2-w2t
        run: |
          git submodule update --init
          cd fshell-w2t
          wget https://codeload.github.com/eliben/pycparser/zip/master -O pycparser-master.zip
          unzip pycparser-master.zip
      - name: Run tests
        run: sbt test
